### ISSUE TITLE
调用DebugMenuSwitchPreference会FC

### ISSUE THREAD

**Issue by zhiyufen** [zhiyufen/DebugMenu#5]
```xml
     Caused by: java.lang.NoSuchMethodException: <init> [class android.content.Context, interface android.util.AttributeSet]
        at java.lang.Class.getConstructor0(Class.java:2320)
        at java.lang.Class.getConstructor(Class.java:1725)
        at android.preference.GenericInflater.createItem(GenericInflater.java:378)
        at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:432) 
        at android.preference.GenericInflater.rInflate(GenericInflater.java:483) 
        at android.preference.GenericInflater.inflate(GenericInflater.java:327) 
        at android.preference.GenericInflater.inflate(GenericInflater.java:264) 
        at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:324) 
        at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:326) 
        at com.android.zhiyufen.debugmenu.demo.DebugMenuDome.DemoDebugMenuFragment.onCreate(DemoDebugMenuFragment.java:16) 
        at android.app.Fragment.performCreate(Fragment.java:2593) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234) 
        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2421) 
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2200) 
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2154) 
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2055) 
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3050) 
        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2997) 
        at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:179) 
        at android.app.Activity.performCreateCommon(Activity.java:7177) 
        at android.app.Activity.performCreate(Activity.java:7185) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6942) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
```

**Comment by zhiyufen** [comment]
#### 解决方案
需要把该类构造方法更改为：DebugMenuSwitchPreference(Context context, AttributeSet attrs) ; 另外复写setChecked方法来存储更改的值；

**Comment by zhiyufen** [comment]
Fixed
